[project]
name = "lrax"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "equinox>=0.13.8",
    "jax[cuda]>=0.10.2",
    "jaxtyping>=0.3.11",
    "lightning>=2.6.5",
    "optax>=0.2.8",
    "pyyaml>=6.0.3",
    "wandb>=0.19.0",
]
