[project]
name = "lrax"
version = "0.1.0"
description = "A collection of modules used by LRAM for robotics learning."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "equinox>=0.13.8",
    "jax[cuda]>=0.10.2",
    "jaxtyping>=0.3.11",
    "lightning>=2.6.5",
    "mujoco-mjx>=3.10.0",
    "optax>=0.2.8",
    "pyyaml>=6.0.3",
    "wandb>=0.19.0",
]

[tool.ruff.lint]
ignore = ["F722", "F821", "E731", "F811"]
