name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Run Ruff linter
        run: uvx ruff@0.16.5 check --output-format=github

      - name: Run Ruff formatter
        run: uvx ruff@0.16.5 format --check

  lock:
    name: Lockfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"

      - name: Check that uv.lock is up to date
        run: uv lock --check
